main_module = { soi ~ statement* ~ eoi }

statement = { effect }

effect = { expression }

expression = { boolean | nil | number | string }

boolean = { "true" | "false" }
nil = { "nil" }

number = @{ "-"? ~ integer ~ ("." ~ '0'..'9'+)? }
integer = @{ "0" | '1'..'9' ~ '0'..'9'* }

string  = @{ "\"" ~ (escape | !("\"" | "\\") ~ any)* ~ "\"" }
escape  = @{ "\\" ~ ("\"" | "\\" | "n" | "r" | "t") }

whitespace = _{ " " | "\t" | "\r" | "\n" }
comment = _{ ";" ~ (!"\n" ~ any)* }
